### ISSUE TITLE
Invalid dictionary with new-style transfer

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/apertium-eo-ca#2]
When converted to new transfer style, the steps `lt-proc -b ca-eo.autobil.bin` and `lt-proc -b ca-eo-translit.autobil.bin` both throw `Error: Invalid dictionary (hint: entry beginning with whitespace)`

**Comment by TinoDidriksen** [comment]
And when building from scratch:
````
Error: Invalid dictionary (hint: entry on the right beginning with whitespace)
make: *** [Makefile:696: ca-eo.autobil.bin] Error 1
Error: Invalid dictionary (hint: entry on the right beginning with whitespace)
make: *** [Makefile:703: ca-eo-translit.autobil.bin] Error 1
````

**Comment by xavivars** [comment]
The whitespace error is fixed, but there's still another one: 

```
apertium-gen-modes modes.xml
cp *.mode modes/
cp: cannot stat '*.mode': No such file or directory
Makefile:811: recipe for target 'modes/ca-eo.mode' failed
make[1]: *** [modes/ca-eo.mode] Error 1
make[1]: Leaving directory '/home/xavi/src/apertium-eo-ca'
Makefile:309: recipe for target 'all' failed
make: *** [all] Error 2
```

I'm sure there's something that needs to be changed in the Makefiles, but I'm not that familiar with those.

**Comment by TinoDidriksen** [comment]
The build system needs fixing, a'la https://github.com/apertium/apertium-eo-es/commit/0555cbdb7682b75a3eba669c2007c43c75a4c87a
